In [1]:
%load_ext autoreload
%autoreload 2

%config IPCompleter.greedy=True

In [2]:
import numpy as np
import h5py

import snapshot_obj

import importlib

In [3]:
importlib.reload(snapshot_obj)

<module 'snapshot_obj' from '/home/kasper/Curvaton_Simulations/APOSTLE_analysis/snapshot_obj.py'>

# Read units

In [5]:
snap = snapshot_obj.Snapshot("V1_LR_fix", 127)
with h5py.File(snap.part_file, 'r') as f:
    for key,val in f['link1/Units'].attrs.items():
        print("{:25} {}".format(key, val))

UnitDensity_in_cgs        6.769911178294543e-31
UnitEnergy_in_cgs         1.989e+53
UnitLength_in_cm          3.085678e+24
UnitMass_in_g             1.989e+43
UnitPressure_in_cgs       6.7699111782945425e-21
UnitTime_in_s             3.085678e+19
UnitVelocity_in_cm_per_s  100000.0


# Mass resolution

## Low resolution run:

In [10]:
sim_id = "CDM_V1_LR"
snap_id = 127
snap = snapshot_obj.Snapshot(sim_id, snap_id)

Gas particle masses have values in the following range (in cgs):

In [7]:
masses = snap.get_particle_masses(part_type=[4])
print(np.min(masses), np.max(masses), np.mean(masses))

1.604584050793082e+39 2.0283306376685773e+40 2.1612382449481833e+39


$2*10^{39}$ grams corresponds to around $10^6$ solar masses.

Dark matter particle masses have values in the following range (in cgs):

In [8]:
masses = snap.get_particle_masses(part_type=[1])
print(np.min(masses), np.max(masses), np.mean(masses))

1.4576205453522563e+40 1.4576205453522563e+40 1.4576205453522546e+40


Star particle masses have values in the following range (in cgs):

In [9]:
masses = snap.get_particle_masses(part_type=[4])
print(np.min(masses), np.max(masses), np.mean(masses))

1.604584050793082e+39 2.0283306376685773e+40 2.1612382449481833e+39


Number of particles in the simulation:

In [23]:
print(snap.get_attribute('NumPart_Total', 'Header'))

[  1042   1123 890351      0      0      0]
[  1042   1123 890351      0      0      0]


## Medium resolution run:

In [6]:
sim_id = "V1_MR_fix"
snap_id = 127
snap = snapshot_obj.Snapshot(sim_id, snap_id)

Gas particle masses have values in the following range (in cgs):

In [7]:
masses = snap.get_particle_masses(part_type=[4])
print(np.min(masses), np.max(masses), np.mean(masses))

1.3087246887654272e+38 1.3147677006744827e+39 1.730342534199397e+38


$2*10^{39}$ grams corresponds to around $10^6$ solar masses.

Dark matter particle masses have values in the following range (in cgs):

In [8]:
masses = snap.get_particle_masses(part_type=[1])
print(np.min(masses), np.max(masses), np.mean(masses))

1.1911403675329331e+39 1.1911403675329331e+39 1.1911403675329432e+39


Star particle masses have values in the following range (in cgs):

In [9]:
masses = snap.get_particle_masses(part_type=[4])
print(np.min(masses), np.max(masses), np.mean(masses))

1.3087246887654272e+38 1.3147677006744827e+39 1.730342534199397e+38


Number of particles in the simulation:

In [10]:
print(snap.get_attribute('NumPart_Total', 'Header'))

[   12577    13548 14304577        0        0        0]
