In [1]:
%load_ext autoreload
%autoreload 2

%config IPCompleter.greedy=True

In [2]:
import numpy as np
import importlib

import data_file_manipulation
import simulation
import halo_matching
import snapshot_obj 
import simulation_tracing

In [3]:
importlib.reload(data_file_manipulation)
importlib.reload(simulation)
importlib.reload(halo_matching)
importlib.reload(snapshot_obj)
importlib.reload(simulation_tracing)

<module 'simulation_tracing' from '/home/kassiili/Curvaton_Simulations/analysis/simulation_tracing.py'>

In [4]:
sim_id = "V1_LR_fix"
print(data_file_manipulation.get_snap_ids(sim_id))

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127]


In [20]:
sim = simulation.Simulation(sim_id)
print(sim.get_snap_num())
print(sim.get_snap_ids())

128
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127]


In [6]:
snap1 = snapshot_obj.Snapshot("V1_LR_fix", 127)
snap2 = snapshot_obj.Snapshot("V1_LR_fix", 126) 
matcher = halo_matching.SnapshotMatcher()

In [9]:
matches_in1, matches_in2 = matcher.match_snapshots(snap1, snap2)

In [8]:
snap = snapshot_obj.Snapshot("V1_LR_fix", 123)
print(data_file_manipulation.group_dataset_exists(snap, "Descendants", "Extended/Heritage/BackwardBranching"))
test = snap.get_subhalos("Descendants", group="Extended/Heritage/BackwardBranching")
print(test)
print(data_file_manipulation.group_dataset_exists(snap, "Descendants", "Extended/Heritage/BackwardBranching"))

True
[         0          1          2 ... 4294967296 4294967296 4294967296]
True


In [10]:
print(matches_in1[:100])

[         0          1        241          2          3          4
          5          7          8          6          9         10
         11         12         14         13         15         16
         17         23         20         19         21         22
         25 4294967296         24         32         30         28
         29         31         34 4294967296 4294967296        478
         42        242 4294967296 4294967296 4294967296 4294967296
 4294967296 4294967296 4294967296 4294967296 4294967296 4294967296
 4294967296 4294967296 4294967296 4294967296 4294967296 4294967296
 4294967296         60         61         62        201         63
         64         65         66         67         68         69
         70         71         72         73         74         76
        376         78         77 4294967296         79         81
        454         82         80        202         83         92
         84         89         86         87 4294967296       

In [11]:
print(matches_in2[:100])

[[         0 4294967296 4294967296]
 [         1 4294967296 4294967296]
 [         3 4294967296 4294967296]
 [         4 4294967296 4294967296]
 [         5 4294967296 4294967296]
 [         6 4294967296 4294967296]
 [         9 4294967296 4294967296]
 [         7 4294967296 4294967296]
 [         8 4294967296 4294967296]
 [        10 4294967296 4294967296]
 [        11 4294967296 4294967296]
 [        12 4294967296 4294967296]
 [        13 4294967296 4294967296]
 [        15 4294967296 4294967296]
 [        14 4294967296 4294967296]
 [        16 4294967296 4294967296]
 [        17 4294967296 4294967296]
 [        18 4294967296 4294967296]
 [       411 4294967296 4294967296]
 [        21 4294967296 4294967296]
 [        20 4294967296 4294967296]
 [        22 4294967296 4294967296]
 [        23 4294967296 4294967296]
 [        19 4294967296 4294967296]
 [        26 4294967296 4294967296]
 [        24 4294967296 4294967296]
 [4294967296 4294967296 4294967296]
 [4294967296 4294967296 4294

In [9]:
merger_tree = simulation_tracing.MergerTree(sim, matcher, branching="backward")

In [10]:
tracer_dict = merger_tree.trace_all(123, 127)

In [11]:
print(tracer_dict.keys())
print(tracer_dict[123].keys())
print(tracer_dict[124].keys())
print(tracer_dict[127].keys())

dict_keys([123, 124, 125, 126, 127])
dict_keys(['Descendants'])
dict_keys(['Progenitors', 'Descendants'])
dict_keys(['Progenitors'])


In [14]:
snap_123 = snapshot_obj.Snapshot(sim_id, 123)
matches_123 = snap_123.get_subhalos("Descendants", group="Extended/Heritage/BackwardBranching")

In [21]:
print(matches_123.size)
print(matches_123[:100])

1127
[         0          1          2          3          4          6
          5         11          9         10         12         18
         14         15         16         17         22         23
         20         19         24         30         27         29
         33         32 4294967296         37         34 4294967296
         38 4294967296 4294967296 4294967296 4294967296 4294967296
 4294967296 4294967296 4294967296 4294967296 4294967296 4294967296
 4294967296 4294967296 4294967296 4294967296 4294967296 4294967296
 4294967296 4294967296         54         55         56         57
        306         59         58         60         61         62
         64         63 4294967296         65         66         67
         71         72         70         73 4294967296         74
         69         75         76         77        427         78
         79         88         80         93         82         86
 4294967296         81        566         84 4294967296  

In [39]:
snap_124 = snapshot_obj.Snapshot(sim_id, 124)
matches_124 = snap_124.get_subhalos("Progenitors", group="Extended/Heritage/BackwardBranching")

In [40]:
print(matches_124.size)
#print(matches_124[:100])
print(np.sum(matches_124[:,1] < 1000000))

3357
0


In [23]:
print(merger_tree.get_all_matches())

100
Extended/Heritage/BackwardBranching
0 0
101
Extended/Heritage/BackwardBranching
0 0
102
Extended/Heritage/BackwardBranching
0 0
103
Extended/Heritage/BackwardBranching
0 0
104
Extended/Heritage/BackwardBranching
0 0
105
Extended/Heritage/BackwardBranching
0 0
106
Extended/Heritage/BackwardBranching
0 0
107
Extended/Heritage/BackwardBranching
0 0
108
Extended/Heritage/BackwardBranching
0 0
109
Extended/Heritage/BackwardBranching
0 0
110
Extended/Heritage/BackwardBranching
0 0
111
Extended/Heritage/BackwardBranching
0 0
112
Extended/Heritage/BackwardBranching
0 0
113
Extended/Heritage/BackwardBranching
0 0
114
Extended/Heritage/BackwardBranching
0 0
115
Extended/Heritage/BackwardBranching
0 0
116
Extended/Heritage/BackwardBranching
0 0
117
Extended/Heritage/BackwardBranching
0 0
118
Extended/Heritage/BackwardBranching
0 0
119
Extended/Heritage/BackwardBranching
0 0
120
Extended/Heritage/BackwardBranching
0 0
121
Extended/Heritage/BackwardBranching
0 0
122
Extended/Heritage/BackwardBr

In [42]:
merger_tree.store_tracer()

100
Extended/Heritage/BackwardBranching
0 0
101
Extended/Heritage/BackwardBranching
0 0
102
Extended/Heritage/BackwardBranching
0 0
103
Extended/Heritage/BackwardBranching
0 0
104
Extended/Heritage/BackwardBranching
0 0
105
Extended/Heritage/BackwardBranching
0 0
106
Extended/Heritage/BackwardBranching
0 0
107
Extended/Heritage/BackwardBranching
0 0
108
Extended/Heritage/BackwardBranching
0 0
109
Extended/Heritage/BackwardBranching
0 0
110
Extended/Heritage/BackwardBranching
0 0
111
Extended/Heritage/BackwardBranching
0 0
112
Extended/Heritage/BackwardBranching
0 0
113
Extended/Heritage/BackwardBranching
0 0
114
Extended/Heritage/BackwardBranching
0 0
115
Extended/Heritage/BackwardBranching
0 0
116
Extended/Heritage/BackwardBranching
0 0
117
Extended/Heritage/BackwardBranching
0 0
118
Extended/Heritage/BackwardBranching
0 0
119
Extended/Heritage/BackwardBranching
0 0
120
Extended/Heritage/BackwardBranching
0 0
121
Extended/Heritage/BackwardBranching
0 0
122
Extended/Heritage/BackwardBr

{123: {'Descendants': array([         0,          1,          2, ..., 4294967296, 4294967296,
         4294967296])},
 124: {'Descendants': array([         0,          1,          3, ..., 4294967296, 4294967296,
         4294967296]),
  'Progenitors': array([[         0, 4294967296, 4294967296],
         [         1, 4294967296, 4294967296],
         [         2, 4294967296, 4294967296],
         ...,
         [4294967296, 4294967296, 4294967296],
         [4294967296, 4294967296, 4294967296],
         [4294967296, 4294967296, 4294967296]])},
 125: {'Descendants': array([         0,          1,          2, ..., 4294967296, 4294967296,
         4294967296]),
  'Progenitors': array([[         0, 4294967296, 4294967296],
         [         1, 4294967296, 4294967296],
         [       266, 4294967296, 4294967296],
         ...,
         [4294967296, 4294967296, 4294967296],
         [4294967296, 4294967296, 4294967296],
         [4294967296, 4294967296, 4294967296]])},
 126: {'Descendants'

In [22]:
merger_tree.read_from_storage()

123
123
124
124
125
125
126
126
127
127


{123: {'Descendants': array([         0,          1,          2, ..., 4294967296, 4294967296,
         4294967296])},
 124: {'Descendants': array([         0,          1,          3, ..., 4294967296, 4294967296,
         4294967296]),
  'Progenitors': array([[         0, 4294967296, 4294967296],
         [         1, 4294967296, 4294967296],
         [         2, 4294967296, 4294967296],
         ...,
         [4294967296, 4294967296, 4294967296],
         [4294967296, 4294967296, 4294967296],
         [4294967296, 4294967296, 4294967296]])},
 125: {'Descendants': array([         0,          1,          2, ..., 4294967296, 4294967296,
         4294967296]),
  'Progenitors': array([[         0, 4294967296, 4294967296],
         [         1, 4294967296, 4294967296],
         [       266, 4294967296, 4294967296],
         ...,
         [4294967296, 4294967296, 4294967296],
         [4294967296, 4294967296, 4294967296],
         [4294967296, 4294967296, 4294967296]])},
 126: {'Descendants'

In [49]:
merger_tree.simulation.get_snapshot(123)

In [22]:
msnaps = merger_tree.get_matched_snapshots()
for s in msnaps:
    print(s.snap_id)

123
124
125
126
127


In [23]:
print(merger_tree.get_redshifts())

[1.00638512e-01 7.45670680e-02 4.91132026e-02 2.42622770e-02
 2.22044605e-16]


In [24]:
snap_tracer = simulation_tracing.SnapshotTracer(123, merger_tree)

tracer = snap_tracer.trace(127)

In [25]:
print(tracer[40:70, -6:])

[[4294967296         40 4294967296 4294967296 4294967296 4294967296]
 [4294967296         41 4294967296 4294967296 4294967296 4294967296]
 [4294967296         42 4294967296 4294967296 4294967296 4294967296]
 [4294967296         43 4294967296 4294967296 4294967296 4294967296]
 [4294967296         44 4294967296 4294967296 4294967296 4294967296]
 [4294967296         45 4294967296 4294967296 4294967296 4294967296]
 [4294967296         46 4294967296 4294967296 4294967296 4294967296]
 [4294967296         47 4294967296 4294967296 4294967296 4294967296]
 [4294967296         48 4294967296 4294967296 4294967296 4294967296]
 [4294967296         49 4294967296 4294967296 4294967296 4294967296]
 [4294967296         50         54         59         60         55]
 [4294967296         51         55         60         62         57]
 [4294967296         52         56         61         61         56]
 [4294967296         53         57         62         63         59]
 [4294967296         54        306